### ISSUE TITLE
Collaboration Inquiry

### ISSUE THREAD

**Issue by zk-steve** [0xPolygonMiden/clob-example#4]
Hi @phklive,

I’m Steve, and I lead a team working in the Zero-Knowledge (ZK) field. I came across this repository last week after seeing your demo in Bangkok and found it really interesting. I also heard that you’re looking for potential partners for this project, so I’d love to discuss collaboration opportunities.

In addition to our expertise in ZK, my team has experience building both decentralized (DEX) and centralized (CEX) exchanges.

Looking forward to hearing from you!

Best regards,
Steve

**Comment by phklive** [comment]
Hello @zk-steve, feel free to contact me on Telegram to discuss further (same handle)
